// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDK8r0q_3qXfXFDtxC9QU_HOO8fL_faPY',
    appId: '1:100737778699:web:34e35ff35545ba5498730e',
    messagingSenderId: '100737778699',
    projectId: 'game-recommendation-c9ffa',
    authDomain: 'game-recommendation-c9ffa.firebaseapp.com',
    storageBucket: 'game-recommendation-c9ffa.appspot.com',
    measurementId: 'G-ZV07QFV1M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCai-2RmaFRNSjduPHYcbHedDt3NPW3cek',
    appId: '1:100737778699:android:7e4b224b4371c16f98730e',
    messagingSenderId: '100737778699',
    projectId: 'game-recommendation-c9ffa',
    storageBucket: 'game-recommendation-c9ffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvUj2Wr4fP-Ro247LMC1-QfO-2xgBFtBo',
    appId: '1:100737778699:ios:439cb45275ff904698730e',
    messagingSenderId: '100737778699',
    projectId: 'game-recommendation-c9ffa',
    storageBucket: 'game-recommendation-c9ffa.appspot.com',
    iosBundleId: 'com.example.gameRecommend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvUj2Wr4fP-Ro247LMC1-QfO-2xgBFtBo',
    appId: '1:100737778699:ios:aa4f490e0c1815b498730e',
    messagingSenderId: '100737778699',
    projectId: 'game-recommendation-c9ffa',
    storageBucket: 'game-recommendation-c9ffa.appspot.com',
    iosBundleId: 'com.example.gameRecommend.RunnerTests',
  );
}
